# Generated by Django 5.2.17 on 2026-08-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_leavetype_profilechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_carry_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_hourly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='attachment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='attachment_rule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='deduct_quota',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='minimum_unit',
            field=models.CharField(default='1 天', max_length=30),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='quota_type',
            field=models.CharField(default='固定年度額度', max_length=30),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_manager_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='default_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
