# Generated by Django 5.2.17 on 2026-08-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_announcement_attachment_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
