# Generated by Django 5.2.17 on 2026-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_user_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
    ]
