# Generated by Django 5.2.17 on 2026-08-18 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_leave_request_type_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpLeaveDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_leave_drafts', to=settings.AUTH_USER_MODEL)),
                ('submitted_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_draft', to='hr.leaverequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
